import React from "react";
import Link from "next/link";
import { FileText, Cpu, Eye, Image as ImageIcon, ArrowRight } from "lucide-react";

export default function ChunkingPage() {
  return (
    <div>
      <div className="flex items-center gap-2 mb-2 text-accent-cyan text-sm font-semibold tracking-wider uppercase">
        <FileText className="h-4 w-4" /> Ingestion & Chunking
      </div>
      <h1>Ingestion Pipeline & Contextual Chunking</h1>
      <p className="text-text-secondary leading-relaxed">
        The ingestion module processes multi-format documents (PDF, DOCX, MD, and code scripts), normalizes the content, splits it into digestible chunks, and embeds them into the database.
      </p>

      <h2>Multi-Format File Loaders</h2>
      <p>
        The ingestion system supports recursive directory crawling and handles files according to their file extensions:
      </p>
      <ul>
        <li><strong>PDF Files:</strong> Handled by <code>pdfplumber</code> to extract layout-aware text along with page metadata.</li>
        <li><strong>DOCX Files:</strong> Parsed using <code>python-docx</code> to extract paragraph text, headings, and tabular cells.</li>
        <li><strong>Markdown:</strong> Scrapes structural indicators (headers, blockquotes, raw links).</li>
        <li><strong>Code Files:</strong> Handles developer code files (e.g. <code>.py</code>, <code>.js</code>, <code>.ts</code>, <code>.java</code>) with specific code split rules.</li>
      </ul>

      <h2>Scanned PDF Support (ONNX OCR Fallback)</h2>
      <p>
        Standard loaders extract blank text if a PDF contains only scanned images (e.g., scanned resumes or scanned forms). To solve this, our loader integrates a **local OCR fallback pipeline** using <code>rapidocr-onnxruntime</code>:
      </p>
      <div className="my-4 p-4 bg-bg-surface border border-border-muted rounded-lg flex items-center gap-4">
        <div className="p-3 rounded-lg bg-orange-500/10 text-orange-400 border border-orange-500/20">
          <ImageIcon className="h-6 w-6" />
        </div>
        <div className="text-sm">
          <span className="font-semibold text-white block">OCR Fallback Trigger</span>
          <span className="text-text-secondary">If pdfplumber returns 0 text extraction characters, the loader renders each page to an image and runs a local RapidOCR ONNX model to extract characters, ensuring zero-configuration OCR capability.</span>
        </div>
      </div>

      <h2>Chunking Strategies</h2>
      <p>
        RAG performance relies heavily on chunk boundaries. We implement 5 strategies in <code>src/ingestion/chunker.py</code>:
      </p>
      <div className="space-y-3 my-6">
        <div className="p-3.5 bg-bg-surface border border-border-muted rounded-lg">
          <h4 className="font-semibold text-white text-sm m-0">1. Fixed-Size Chunking</h4>
          <p className="text-xs text-text-secondary m-1">Splits text into fixed sizes (e.g. 512 tokens) with a sliding overlap (e.g. 50 tokens). Fast but frequently cuts off sentences in the middle.</p>
        </div>
        <div className="p-3.5 bg-bg-surface border border-border-muted rounded-lg">
          <h4 className="font-semibold text-white text-sm m-0">2. Recursive Text Splitting</h4>
          <p className="text-xs text-text-secondary m-1">Splits text recursively using delimiters (paragraphs <code>\n\n</code>, lines <code>\n</code>, sentences, and words) until size constraints are satisfied, maintaining paragraph integrity.</p>
        </div>
        <div className="p-3.5 bg-bg-surface border border-border-muted rounded-lg">
          <h4 className="font-semibold text-white text-sm m-0">3. Markdown Chunking</h4>
          <p className="text-xs text-text-secondary m-1">Splits content according to markdown headers (<code>#</code>, <code>##</code>, <code>###</code>), grouping topics together.</p>
        </div>
        <div className="p-3.5 bg-bg-surface border border-border-muted rounded-lg">
          <h4 className="font-semibold text-white text-sm m-0">4. Semantic Chunking</h4>
          <p className="text-xs text-text-secondary m-1">Computes embeddings for each sentence, calculates similarity between adjacent sentences, and places chunk boundaries where cosine similarity drops below a statistical threshold.</p>
        </div>
        <div className="p-3.5 bg-bg-surface border border-border-muted rounded-lg">
          <h4 className="font-semibold text-white text-sm m-0">5. Contextual Chunking (SOTA)</h4>
          <p className="text-xs text-text-secondary m-1">Prepends a global context summary generated by the LLM to each individual chunk content before indexing, mitigating context loss during vector retrieval.</p>
        </div>
      </div>

      <h2>State-of-the-Art Contextual Chunking</h2>
      <p>
        During ingestion, the chunker reads the first 4,000 characters of a document and triggers a fast local LLM completion to construct a document context summary. For each chunk, it wraps the content with this context summary:
      </p>

      <pre>
        <code>{`# Context Injection Template
CONTEXT_TEMPLATE = """
You are a context injector. Given a document and a small chunk of text from it, write a short (1-2 sentences) context statement that situates this chunk within the overall document.
Do not summarize the chunk itself.

Overall Document:
{document_context}

Chunk to situate:
{chunk_content}

Output only the 1-2 sentence context statement, nothing else.
"""

# Resulting Chunk Indexed:
# <Document Context: [Summary]> [Actual original chunk text content]`}</code>
      </pre>

      <div className="doc-alert doc-alert-tip">
        <strong>Result:</strong> By prepending the context summary, standard dense embeddings preserve crucial identifiers (like project names, document subjects, and core authors) that would otherwise be missing from a tiny text block.
      </div>

      <h2>Configuring Chunking</h2>
      <p>
        Open <code>config.yaml</code> to choose your strategy:
      </p>
      <pre>
        <code>{`chunking:
  strategy: "contextual" # Options: fixed, recursive, semantic, markdown, contextual
  chunk_size: 512
  chunk_overlap: 50
  semantic_threshold: 0.82`}</code>
      </pre>

      <div className="mt-8 flex justify-between">
        <Link 
          href="/architecture/" 
          className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-border-muted text-text-secondary hover:text-text-primary transition-colors"
        >
          Back to Architecture
        </Link>
        <Link 
          href="/retrieval/" 
          className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg bg-gradient-to-r from-accent-start to-accent-end text-white font-medium hover:shadow-glow transition-all"
        >
          <span>Continue to Retrieval</span>
          <ArrowRight className="h-4 w-4" />
        </Link>
      </div>
    </div>
  );
}
